server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html mapper.html;

    # Gzip Compression untuk performa cepat
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    gzip_min_length 1000;

    # Caching asset statis (JS, CSS, PNG, JPG, SVG)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|otf|svg|map)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
        try_files $uri =404;
    }

    # Halaman Utama (Denah Interaktif PLTGU)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Halaman Mapper (Alat Pemetaan Titik Bangunan)
    location /mapper {
        try_files $uri $uri/ /mapper.html;
    }

    # Error pages
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
